# Generated by Django 4.2.1 on 2023-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_email_post_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
