# Generated by Django 4.2.1 on 2023-05-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post_comment'),
        ),
    ]
