# Generated by Django 4.2.1 on 2023-05-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_comment',
            old_name='timestamp',
            new_name='Date',
        ),
    ]
