# Generated by Django 4.2.1 on 2023-05-20 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_timestamp_post_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post_comment'),
        ),
    ]
