# Generated by Django 4.2.1 on 2023-05-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_comment_date_alter_post_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IMAGE_POST_B',
            field=models.ImageField(default='secong Image', null=True, upload_to='Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='IMAGE_POST_C',
            field=models.ImageField(default='secong Image', null=True, upload_to='Post'),
        ),
    ]
