# Generated by Django 4.2.1 on 2023-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_image_post_b_remove_post_image_post_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='user',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
