# Generated by Django 4.2.1 on 2023-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_comment_website_alter_post_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Recommended', 'Recommended'), ('Inspirations', 'Inspirations'), ('Latest_Post', 'Latest_Post')], default='', max_length=200),
        ),
    ]
